### ISSUE TITLE
Error when plugin is used on elements lacking class attributes

### ISSUE THREAD

**Issue by LordPachelbel** [tiagoporto/jquery-svg-to-inline#17]
Here is how I'm selecting `<img>` tags that have no class attribute but whose filenames end with `.svg`:
`$('#content img[src*=".svg"]');`

When the plugin is called on the resulting jQuery collection, ...
(like this):
`$('#content img[src*=".svg"]').svgToInline();`

...then the browser console reports this error:
```
TypeError: $(...).attr(...) is undefined
debugger eval code:29:26
```

The error is from line 29 which assumes that the tag has a class attribute :
`inputClass = $(this).attr('class').split(' '),`

My workaround is to do this:
`$('#content img[src*=".svg"]').addClass('svg').svgToInline();`

But ideally that wouldn't be necessary.

Other than that minor thing, this plugin works really well. Thanks!

**Comment by tiagoporto** [comment]
Hi @LordPachelbel sorry for the lack.
I'm working in a new version. I can fix it.
Thanks

**Comment by tiagoporto** [comment]
@LordPachelbel I rewrote this lib [github.com/tiagoporto/svg-to-inline](https://github.com/tiagoporto/svg-to-inline).
